// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysUser is the golang structure of table sys_user for DAO operations like Where/Data.
type SysUser struct {
	g.Meta     `orm:"table:sys_user, do:true"`
	UserId     interface{} // 用户ID
	UserName   interface{} // 用户账号
	Password   interface{} // 密码
	DeptId     interface{} // 部门ID
	NickName   interface{} // 用户昵称
	UserType   interface{} // 用户类型 1超级管理员 2普通用户 默认2
	Email      interface{} // 用户邮箱
	Phone      interface{} // 手机号码
	Sex        interface{} // 用户性别 1男 2女 3未知 默认1
	Avatar     interface{} // 头像地址
	Status     interface{} // 帐号状态 1正常 2停用 默认1
	DelFlag    interface{} // 删除标志 1正常 2删除 默认1
	LoginIp    interface{} // 最后登录IP
	CreateBy   interface{} // 创建者 默认1
	UpdateBy   interface{} // 更新者 默认1
	Remark     interface{} // 备注
	LoginDate  *gtime.Time // 最后登录时间
	CreateTime *gtime.Time // 创建时间
	UpdateTime *gtime.Time // 更新时间
}
