// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysFile is the golang structure of table sys_file for DAO operations like Where/Data.
type SysFile struct {
	g.Meta       `orm:"table:sys_file, do:true"`
	Id           interface{} //
	FileOldName  interface{} // 原文件名
	FileName     interface{} // 文件名
	FileType     interface{} // 文件类型
	FileSize     interface{} // 文件大小 M
	FileLocation interface{} // 文件位置
	FileUrl      interface{} // 文件url
	CreateTime   *gtime.Time // 上传时间
	CreateBy     interface{} // 上传人
}
