// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package do

import (
	"github.com/gogf/gf/v2/frame/g"
	"github.com/gogf/gf/v2/os/gtime"
)

// SysMenu is the golang structure of table sys_menu for DAO operations like Where/Data.
type SysMenu struct {
	g.Meta     `orm:"table:sys_menu, do:true"`
	MenuId     interface{} // 菜单ID
	MenuName   interface{} // 菜单名称
	ParentId   interface{} // 父菜单ID 默认0
	OrderNum   interface{} // 显示顺序 默认0
	Path       interface{} // 路由地址
	Component  interface{} // 组件路径
	Query      interface{} // 路由参数
	IsFrame    interface{} // 是否为外链 1否 2是 默认1
	IsCache    interface{} // 是否缓存 1缓存 2不缓存 默认1
	MenuType   interface{} // 菜单类型（1目录 2菜单 3按钮）
	Visible    interface{} // 菜单状态 1显示 2隐藏 默认1
	Status     interface{} // 菜单状态 1正常 2停用 默认1
	Perms      interface{} // 权限标识
	Icon       interface{} // 菜单图标 默认'#'
	CreateBy   interface{} // 创建者 默认1
	UpdateBy   interface{} // 更新者 默认1
	Remark     interface{} // 备注
	CreateTime *gtime.Time // 创建时间
	UpdateTime *gtime.Time // 更新时间
}
