// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// HhMenuDao is the data access object for table hh_menu.
type HhMenuDao struct {
	table   string        // table is the underlying table name of the DAO.
	group   string        // group is the database configuration group name of current DAO.
	columns HhMenuColumns // columns contains all the column names of Table for convenient usage.
}

// HhMenuColumns defines and stores column names for table hh_menu.
type HhMenuColumns struct {
	MenuId     string // 菜单ID
	MenuName   string // 菜单名称
	ParentId   string // 父菜单ID 默认0
	OrderNum   string // 显示顺序 默认0
	Path       string // 路由地址
	Component  string // 组件路径
	Query      string // 路由参数
	IsFrame    string // 是否为外链 1否 2是 默认1
	IsCache    string // 是否缓存 1缓存 2不缓存 默认1
	MenuType   string // 菜单类型（1目录 2菜单 3按钮）
	Visible    string // 菜单状态 1显示 2隐藏 默认1
	Status     string // 菜单状态 1正常 2停用 默认1
	Perms      string // 权限标识
	Icon       string // 菜单图标 默认'#'
	CreateBy   string // 创建者 默认1
	UpdateBy   string // 更新者 默认1
	Remark     string // 备注
	CreateTime string // 创建时间
	UpdateTime string // 更新时间
}

// hhMenuColumns holds the columns for table hh_menu.
var hhMenuColumns = HhMenuColumns{
	MenuId:     "menu_id",
	MenuName:   "menu_name",
	ParentId:   "parent_id",
	OrderNum:   "order_num",
	Path:       "path",
	Component:  "component",
	Query:      "query",
	IsFrame:    "is_frame",
	IsCache:    "is_cache",
	MenuType:   "menu_type",
	Visible:    "visible",
	Status:     "status",
	Perms:      "perms",
	Icon:       "icon",
	CreateBy:   "create_by",
	UpdateBy:   "update_by",
	Remark:     "remark",
	CreateTime: "create_time",
	UpdateTime: "update_time",
}

// NewHhMenuDao creates and returns a new DAO object for table data access.
func NewHhMenuDao() *HhMenuDao {
	return &HhMenuDao{
		group:   "default",
		table:   "hh_menu",
		columns: hhMenuColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *HhMenuDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *HhMenuDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *HhMenuDao) Columns() HhMenuColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *HhMenuDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *HhMenuDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *HhMenuDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
