// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// HhRoleDao is the data access object for table hh_role.
type HhRoleDao struct {
	table   string        // table is the underlying table name of the DAO.
	group   string        // group is the database configuration group name of current DAO.
	columns HhRoleColumns // columns contains all the column names of Table for convenient usage.
}

// HhRoleColumns defines and stores column names for table hh_role.
type HhRoleColumns struct {
	RoleId            string // 角色ID
	RoleName          string // 角色名称
	RoleKey           string // 角色权限字符串
	RoleSort          string // 显示顺序
	DataScope         string // 数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）默认2
	MenuCheckStrictly string // 菜单树选择项是否关联显示
	DeptCheckStrictly string // 部门树选择项是否关联显示
	Status            string // 角色状态 1正常 2停用 默认1
	DelFlag           string // 删除标志 1正常 2停用 默认1
	CreateBy          string // 创建者 默认0
	UpdateBy          string // 更新者 默认0
	Remark            string // 备注
	CreateTime        string // 创建时间
	UpdateTime        string // 更新时间
}

// hhRoleColumns holds the columns for table hh_role.
var hhRoleColumns = HhRoleColumns{
	RoleId:            "role_id",
	RoleName:          "role_name",
	RoleKey:           "role_key",
	RoleSort:          "role_sort",
	DataScope:         "data_scope",
	MenuCheckStrictly: "menu_check_strictly",
	DeptCheckStrictly: "dept_check_strictly",
	Status:            "status",
	DelFlag:           "del_flag",
	CreateBy:          "create_by",
	UpdateBy:          "update_by",
	Remark:            "remark",
	CreateTime:        "create_time",
	UpdateTime:        "update_time",
}

// NewHhRoleDao creates and returns a new DAO object for table data access.
func NewHhRoleDao() *HhRoleDao {
	return &HhRoleDao{
		group:   "default",
		table:   "hh_role",
		columns: hhRoleColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *HhRoleDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *HhRoleDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *HhRoleDao) Columns() HhRoleColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *HhRoleDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *HhRoleDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *HhRoleDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
