// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"context"

	"github.com/gogf/gf/v2/database/gdb"
	"github.com/gogf/gf/v2/frame/g"
)

// HhUserRoleDao is the data access object for table hh_user_role.
type HhUserRoleDao struct {
	table   string            // table is the underlying table name of the DAO.
	group   string            // group is the database configuration group name of current DAO.
	columns HhUserRoleColumns // columns contains all the column names of Table for convenient usage.
}

// HhUserRoleColumns defines and stores column names for table hh_user_role.
type HhUserRoleColumns struct {
	UserId string // 用户ID
	RoleId string // 角色ID
}

// hhUserRoleColumns holds the columns for table hh_user_role.
var hhUserRoleColumns = HhUserRoleColumns{
	UserId: "user_id",
	RoleId: "role_id",
}

// NewHhUserRoleDao creates and returns a new DAO object for table data access.
func NewHhUserRoleDao() *HhUserRoleDao {
	return &HhUserRoleDao{
		group:   "default",
		table:   "hh_user_role",
		columns: hhUserRoleColumns,
	}
}

// DB retrieves and returns the underlying raw database management object of current DAO.
func (dao *HhUserRoleDao) DB() gdb.DB {
	return g.DB(dao.group)
}

// Table returns the table name of current dao.
func (dao *HhUserRoleDao) Table() string {
	return dao.table
}

// Columns returns all column names of current dao.
func (dao *HhUserRoleDao) Columns() HhUserRoleColumns {
	return dao.columns
}

// Group returns the configuration group name of database of current dao.
func (dao *HhUserRoleDao) Group() string {
	return dao.group
}

// Ctx creates and returns the Model for current DAO, It automatically sets the context for current operation.
func (dao *HhUserRoleDao) Ctx(ctx context.Context) *gdb.Model {
	return dao.DB().Model(dao.table).Safe().Ctx(ctx)
}

// Transaction wraps the transaction logic using function f.
// It rollbacks the transaction and returns the error from function f if it returns non-nil error.
// It commits the transaction and returns nil if function f returns nil.
//
// Note that, you should not Commit or Rollback the transaction in function f
// as it is automatically handled by this function.
func (dao *HhUserRoleDao) Transaction(ctx context.Context, f func(ctx context.Context, tx gdb.TX) error) (err error) {
	return dao.Ctx(ctx).Transaction(ctx, f)
}
