// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

// CasbinRule is the golang structure for table casbin_rule.
type CasbinRule struct {
	Id    uint64 `json:"id"     description:""`
	PType string `json:"p_type" description:""`
	V0    string `json:"v_0"    description:""`
	V1    string `json:"v_1"    description:""`
	V2    string `json:"v_2"    description:""`
	V3    string `json:"v_3"    description:""`
	V4    string `json:"v_4"    description:""`
	V5    string `json:"v_5"    description:""`
}
