// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysPost is the golang structure for table sys_post.
type SysPost struct {
	PostId     int64       `json:"post_id"     description:"岗位ID"`
	PostCode   string      `json:"post_code"   description:"岗位编码"`
	PostName   string      `json:"post_name"   description:"岗位名称"`
	PostSort   int         `json:"post_sort"   description:"显示顺序"`
	Status     int         `json:"status"      description:"状态（1正常 2停用）"`
	DelFlag    int         `json:"del_flag"    description:"删除标志 1正常 2删除 默认1"`
	CreateBy   string      `json:"create_by"   description:"创建者"`
	CreateTime *gtime.Time `json:"create_time" description:"创建时间"`
	UpdateBy   string      `json:"update_by"   description:"更新者"`
	UpdateTime *gtime.Time `json:"update_time" description:"更新时间"`
	Remark     string      `json:"remark"      description:"备注"`
}
