// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysUser is the golang structure for table sys_user.
type SysUser struct {
	UserId     int64       `json:"user_id"     description:"用户ID"`
	UserName   string      `json:"user_name"   description:"用户账号"`
	Password   string      `json:"password"    description:"密码"`
	DeptId     int64       `json:"dept_id"     description:"部门ID"`
	NickName   string      `json:"nick_name"   description:"用户昵称"`
	UserType   int         `json:"user_type"   description:"用户类型 1超级管理员 2普通用户 默认2"`
	Email      string      `json:"email"       description:"用户邮箱"`
	Phone      string      `json:"phone"       description:"手机号码"`
	Sex        int         `json:"sex"         description:"用户性别 1男 2女 3未知 默认1"`
	Avatar     string      `json:"avatar"      description:"头像地址"`
	Status     int         `json:"status"      description:"帐号状态 1正常 2停用 默认1"`
	DelFlag    int         `json:"del_flag"    description:"删除标志 1正常 2删除 默认1"`
	LoginIp    string      `json:"login_ip"    description:"最后登录IP"`
	CreateBy   string      `json:"create_by"   description:"创建者 默认1"`
	UpdateBy   string      `json:"update_by"   description:"更新者 默认1"`
	Remark     string      `json:"remark"      description:"备注"`
	LoginDate  *gtime.Time `json:"login_date"  description:"最后登录时间"`
	CreateTime *gtime.Time `json:"create_time" description:"创建时间"`
	UpdateTime *gtime.Time `json:"update_time" description:"更新时间"`
}
