// =================================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// =================================================================================

package entity

import (
	"github.com/gogf/gf/v2/os/gtime"
)

// SysFile is the golang structure for table sys_file.
type SysFile struct {
	Id           int64       `json:"id"            description:""`
	FileOldName  string      `json:"file_old_name" description:"原文件名"`
	FileName     string      `json:"file_name"     description:"文件名"`
	FileType     string      `json:"file_type"     description:"文件类型"`
	FileSize     int         `json:"file_size"     description:"文件大小 M"`
	FileLocation string      `json:"file_location" description:"文件位置"`
	FileUrl      string      `json:"file_url"      description:"文件url"`
	CreateTime   *gtime.Time `json:"create_time"   description:"上传时间"`
	CreateBy     string      `json:"create_by"     description:"上传人"`
}
